version: '3.7'
services:
  db:
    container_name: dev-naughty-walk-postgre-sql
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_USER: development
      POSTGRES_DB: naughty_walk
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    container_name: dev-naughty-walk-redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
  sql:
